### ISSUE TITLE
SSR Version

### ISSUE THREAD

**Issue by jeremymarc** [BananaBobby/react-awesome-toasts#1]
Make it working with SSR (server side rendering)

**Comment by BananaBobby** [comment]
Thanks for the report, will take a look. I've already removed window used in the package code, still looking for other internal window errors

**Comment by BananaBobby** [comment]
That seems to be an issue with style-loader. Will extract styles before publishing (or maybe will publish both)

**Comment by BananaBobby** [comment]
https://github.com/BananaBobby/react-awesome-toasts/pull/2
