### ISSUE TITLE
custom component & position not applied

### ISSUE THREAD

**Issue by de-phy** [BananaBobby/react-awesome-toasts#5]
Hi

I tried to use your library with a custom component as toast.

I tried both examples (HOC and Wrapper ToastConsumer) but in both cases these two properties were not considered. It always renders the default component on bottom-left.

Is it possible that passed-trough properties component and position are not handled?
If not, could you provide a working example of the usage of a custom component and a different position?

Thank you

**Comment by BananaBobby** [comment]
Hey, @de-phy 
I will check it this evening (in ~ 4 hours) and will create an example with custom component in storybook as well as potentially fixing the issue you've mentioned.

**Comment by blvdmitry** [comment]
I'm back, just checked the code and it looks like it's working fine. 

I've pushed an example with a custom component rendered at custom position: 
https://github.com/BananaBobby/react-awesome-toasts/blob/11fcccac6436077c2058ed8033f0ed76121f5aaf/stories/Toast.story.tsx#L73

Screenshot:
<img width="1430" alt="screen shot 2019-02-27 at 22 20 57" src="https://user-images.githubusercontent.com/887379/53523843-2e924780-3ade-11e9-8730-7d891e38e65b.png">

**Comment by de-phy** [comment]
Hey @BananaBobby 
Thanks to your example I got it to work now too.
Thank you a lot for your help.
I hope you have a great day!
